# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [97]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [96]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [ ]:
x.shape

5. Print the type of the previous array in question 3

In [ ]:
type(x)

6. Print the numpy version and the configuration


In [ ]:
print(np.__version__)

7. Print the dimension of the array in question 3


In [ ]:
x.ndim

8. Create a boolean array with all the True values

In [95]:
x = np.array(x, dtype = 'bool')
x

array([[ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array




In [94]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.ndim

2

10. Create a three dimensional array



In [93]:
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
x.ndim

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [92]:
y = np.arange(10)
y[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [91]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [90]:
x = np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [89]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype('float64')
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [86]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr3 = arr1 * arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [85]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
            [7., 2., 12.]])
arr3 = arr1 == arr2
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [27]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x[x % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [28]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x[x % 2 == 1] = -1
x

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

$a^2$

20. Create a 2d array with 1 on the border and 0 inside

In [57]:
x = np.ones((5, 5))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [64]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1, 1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [63]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0][:]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [79]:
x = np.arange(10).reshape((2, 5))
y = x[0]
y

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [80]:
x = np.arange(10).reshape((2, 5))
y = x[1]
y

array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [84]:
x = np.arange(10).reshape((2, 5))
y = x[0][2], x[1][2]
y

(2, 7)

26. Create a 10x10 array with random values and find the minimum and maximum values

In [134]:
x = np.random.randn(10, 10)
print(x)
print(np.amax(x))
print(np.amin(x))

[[ 2.78638745e-01 -5.14936441e-01  9.65334945e-01 -2.49450622e-01
  -5.02134559e-01 -1.82310267e-01 -7.81482569e-01  5.10420574e-01
   7.37640875e-01  1.56537170e+00]
 [-2.35450365e+00 -5.64190630e-01 -8.56905073e-01  4.46176586e-01
  -8.57554955e-01 -2.27163796e-01 -6.03197255e-02 -6.84085860e-01
   1.45704423e+00  4.93088771e-01]
 [-1.52672238e+00  2.32481967e-03 -7.50762986e-01 -1.43342038e+00
  -1.54611747e-01 -1.59458318e+00  1.49351928e+00 -1.50343580e+00
  -1.06353666e+00 -1.27404049e+00]
 [-2.44060972e-01 -1.31716828e+00  5.45824459e-01  5.31014111e-01
  -3.67781169e-01 -1.08828401e+00 -7.48729835e-01  2.68382343e-01
   3.69544096e-01 -7.79055032e-01]
 [ 4.61979299e-02  7.59229325e-01 -1.32223932e+00 -4.75896902e-01
  -1.04163360e+00 -6.07762261e-01 -3.11203943e-01  1.31243693e+00
   1.15661403e-01  6.60131399e-01]
 [-4.13215436e-01  1.76398240e+00  3.85750972e-01  1.13992707e+00
  -1.54437653e+00 -3.78938278e-02 -1.23237181e+00  3.52495790e-01
  -1.11421511e-01 -5.94976128e-01

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [140]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
x = np.intersect1d(a, b)
x

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [142]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
x = np.where(a == b)
x

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [116]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
x = data[names != "Will"]
x

array([[ 1.75201035,  0.88131135, -0.65183702,  0.48682646],
       [-1.80997553, -1.44339214, -0.09320733,  1.38185126],
       [-0.56445519, -1.22899396, -0.2502738 ,  0.27178838],
       [-0.38100177, -0.55541785, -0.36939677,  0.1740399 ],
       [ 0.67102977, -0.50687144, -1.43503124, -0.39659959]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [117]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
x = data[np.logical_and(names != "Will", names != "Joe")]
x

array([[-0.21098115, -1.98850875, -0.59671567, -1.06179394],
       [ 0.18142482, -2.04921467,  0.44893434, -1.49731713]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [229]:
x = np.arange(1, 16).reshape(5, 3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [270]:
x = np.arange(1, 17).reshape(2, 2, 4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [4]:
x = np.arange(1, 17).reshape(2, 2, 4)
np.swapaxes(x, 0, 1)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [18]:
x = np.arange(10)
y = np.sqrt(x)
y[y < 0.5]= 0
y

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [27]:
x = np.random.randn(1, 5)
y = np.random.randn(1, 10)
print(x)
print(y)
print(np.asarray((np.amax(x), np.amax(y))))

[[1.2036205  0.37600985 1.2541797  0.44025063 1.52944754]]
[[ 0.45050656  0.29919712 -0.58054757 -0.79789491 -0.60806529 -0.44424891
   0.14194753  1.28261885  0.1598211   0.16263662]]
[1.52944754 1.28261885]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
x = np.unique(names)
x

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [32]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
print(result)

[6 7 8 9]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [99]:
, [20.12.20 18:53]
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

print("Actual Array: \n", sampleArray)

sampleArray[:,1] = newColumn

print("After Replacing comlumn: \n", sampleArray)

Actual Array: 
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
After Replacing comlumn: 
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [105]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x, y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [114]:
x = np.random.randn(20)
y = np.cumsum(a, dtype = float)
y

array([ 1.,  3.,  6., 10., 15.])